<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\user;

use \php\Boot;
use \datetime\utils\DateTimeUtils;

/**
 * Represents a Gitea user.
 */
class User {
	/**
	 * @var string
	 * The URL of the user's avatar.
	 */
	public $avatarUrl;
	/**
	 * @var \Date
	 * The creation date.
	 */
	public $created;
	/**
	 * @var string
	 * The mail address.
	 */
	public $email;
	/**
	 * @var string
	 * The full name.
	 */
	public $fullName;
	/**
	 * @var int
	 * The user identifier.
	 */
	public $id;
	/**
	 * @var bool
	 * Value indicating whether this user is an administrator.
	 */
	public $isAdmin;
	/**
	 * @var string
	 * The user locale.
	 */
	public $language;
	/**
	 * @var \Date
	 * The last connection date.
	 */
	public $lastLogin;
	/**
	 * @var string
	 * The name of the user account.
	 */
	public $login;

	/**
	 * Creates a new user.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->login = "";
		$this->lastLogin = null;
		$this->language = "";
		$this->isAdmin = false;
		$this->id = -1;
		$this->fullName = "";
		$this->email = "";
		$this->created = null;
		$this->avatarUrl = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "avatar_url") && is_string(\Reflect::field($data, "avatar_url"))) {
				$this->avatarUrl = \Reflect::field($data, "avatar_url");
			}
			if (\Reflect::hasField($data, "created") && is_string(\Reflect::field($data, "created"))) {
				$this->created = \Date::fromTime((DateTimeUtils::fromString(\Reflect::field($data, "created")) - 62135596800.0) * 1000);
			}
			if (\Reflect::hasField($data, "email") && is_string(\Reflect::field($data, "email"))) {
				$this->email = \Reflect::field($data, "email");
			}
			if (\Reflect::hasField($data, "full_name") && is_string(\Reflect::field($data, "full_name"))) {
				$this->fullName = \Reflect::field($data, "full_name");
			}
			if (\Reflect::hasField($data, "id") && Boot::isOfType(\Reflect::field($data, "id"), Boot::getClass('Int'))) {
				$this->id = \Reflect::field($data, "id");
			}
			if (\Reflect::hasField($data, "is_admin") && is_bool(\Reflect::field($data, "is_admin"))) {
				$this->isAdmin = \Reflect::field($data, "is_admin");
			}
			if (\Reflect::hasField($data, "language") && is_string(\Reflect::field($data, "language"))) {
				$this->language = \Reflect::field($data, "language");
			}
			if (\Reflect::hasField($data, "last_login") && is_string(\Reflect::field($data, "last_login"))) {
				$this->lastLogin = \Date::fromTime((DateTimeUtils::fromString(\Reflect::field($data, "last_login")) - 62135596800.0) * 1000);
			}
			if (\Reflect::hasField($data, "login") && is_string(\Reflect::field($data, "login"))) {
				$this->login = \Reflect::field($data, "login");
			}
		}
	}
}

Boot::registerClass(User::class, 'gitea.user.User');
