<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\user;

use \php\Boot;

/**
 * Represents the data needed to create a user heatmap.
 */
class UserHeatmapData {
	/**
	 * @var int
	 * The contribution number.
	 */
	public $contributions;
	/**
	 * @var \Date
	 * The contributions date.
	 */
	public $timestamp;

	/**
	 * Creates a new heatmap data.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->timestamp = \Date::now();
		$this->contributions = 0;
		if ($data !== null) {
			if (\Reflect::hasField($data, "contributions")) {
				$this->contributions = \Reflect::field($data, "contributions");
			}
			if (\Reflect::hasField($data, "timestamp")) {
				$this->timestamp = \Date::fromTime(\Reflect::field($data, "timestamp") * 1000);
			}
		}
	}
}

Boot::registerClass(UserHeatmapData::class, 'gitea.user.UserHeatmapData');
