<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\user;

use \php\Boot;

/**
 * Represents the data needed to create a user heatmap.
 */
class UserHeatmapData {
	/**
	 * @var int
	 * The contribution number.
	 */
	public $contributions;
	/**
	 * @var \Date
	 * The contributions date.
	 */
	public $timestamp;

	/**
	 * Creates a new heatmap data from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return UserHeatmapData
	 */
	public static function fromJson ($map) {
		$tmp = (\Reflect::hasField($map, "timestamp") ? \Date::fromTime(\Reflect::field($map, "timestamp") * 1000) : \Date::now());
		return new UserHeatmapData($tmp, (\Reflect::hasField($map, "contributions") ? \Reflect::field($map, "contributions") : 0));
	}

	/**
	 * Creates a new heatmap data.
	 * 
	 * @param \Date $timestamp
	 * @param int $contributions
	 * 
	 * @return void
	 */
	public function __construct ($timestamp, $contributions = 0) {
		if ($contributions === null) {
			$contributions = 0;
		}
		$this->contributions = $contributions;
		$this->timestamp = $timestamp;
	}
}

Boot::registerClass(UserHeatmapData::class, 'gitea.user.UserHeatmapData');
