<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents settings for an external tracker.
 */
class ExternalTracker {
	/**
	 * @var string
	 * The URL format.
	 */
	public $format;
	/**
	 * @var string
	 * The number format.
	 */
	public $style;
	/**
	 * @var string
	 * The URL of the external issue tracker.
	 */
	public $url;

	/**
	 * Creates a new external tracker from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return ExternalTracker
	 */
	public static function fromJson ($map) {
		$model = new ExternalTracker((\Reflect::hasField($map, "external_tracker_url") ? \Reflect::field($map, "external_tracker_url") : ""));
		if (\Reflect::hasField($map, "external_tracker_format")) {
			$model->format = \Reflect::field($map, "external_tracker_format");
		}
		if (\Reflect::hasField($map, "external_tracker_style")) {
			$model->style = \Reflect::field($map, "external_tracker_style");
		}
		return $model;
	}

	/**
	 * Creates a new external tracker.
	 * 
	 * @param string $url
	 * 
	 * @return void
	 */
	public function __construct ($url) {
		$this->style = "numeric";
		$this->format = "";
		$this->url = $url;
	}
}

Boot::registerClass(ExternalTracker::class, 'gitea.repository.ExternalTracker');
