<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents settings for an external wiki.
 */
class ExternalWiki {
	/**
	 * @var string
	 * The URL of the external wiki.
	 */
	public $url;

	/**
	 * Creates a new external wiki from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return ExternalWiki
	 */
	public static function fromJson ($map) {
		return new ExternalWiki((\Reflect::hasField($map, "external_wiki_url") ? \Reflect::field($map, "external_wiki_url") : ""));
	}

	/**
	 * Creates a new external wiki.
	 * 
	 * @param string $url
	 * 
	 * @return void
	 */
	public function __construct ($url) {
		$this->url = $url;
	}
}

Boot::registerClass(ExternalWiki::class, 'gitea.repository.ExternalWiki');
