<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents settings for an external tracker.
 */
class ExternalTracker {
	/**
	 * @var string
	 * The URL format.
	 */
	public $format;
	/**
	 * @var string
	 * The number format.
	 */
	public $style;
	/**
	 * @var string
	 * The URL of the external issue tracker.
	 */
	public $url;

	/**
	 * Creates a new external tracker.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->url = "";
		$this->style = "numeric";
		$this->format = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "external_tracker_format")) {
				$this->format = \Reflect::field($data, "external_tracker_format");
			}
			if (\Reflect::hasField($data, "external_tracker_style")) {
				$this->style = \Reflect::field($data, "external_tracker_style");
			}
			if (\Reflect::hasField($data, "external_tracker_url")) {
				$this->url = \Reflect::field($data, "external_tracker_url");
			}
		}
	}
}

Boot::registerClass(ExternalTracker::class, 'gitea.repository.ExternalTracker');
