<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents settings for an internal tracker.
 */
class InternalTracker {
	/**
	 * @var bool
	 * Value indicating whether to allow only contributors to track time.
	 */
	public $allowOnlyContributorsToTrackTime;
	/**
	 * @var bool
	 * Value indicating whether to enable dependencies for issues and pull requests.
	 */
	public $enableIssueDependencies;
	/**
	 * @var bool
	 * Value indicating whether to enable the time tracking.
	 */
	public $enableTimeTracker;

	/**
	 * Creates a new internal tracker from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return InternalTracker
	 */
	public static function fromJson ($map) {
		$model = new InternalTracker();
		if (\Reflect::hasField($map, "allow_only_contributors_to_track_time")) {
			$model->allowOnlyContributorsToTrackTime = \Reflect::field($map, "allow_only_contributors_to_track_time");
		}
		if (\Reflect::hasField($map, "enable_issue_dependencies")) {
			$model->enableIssueDependencies = \Reflect::field($map, "enable_issue_dependencies");
		}
		if (\Reflect::hasField($map, "enable_time_tracker")) {
			$model->enableTimeTracker = \Reflect::field($map, "enable_time_tracker");
		}
		return $model;
	}

	/**
	 * Creates a new internal tracker.
	 * 
	 * @return void
	 */
	public function __construct () {
		$this->enableTimeTracker = false;
		$this->enableIssueDependencies = false;
		$this->allowOnlyContributorsToTrackTime = false;
	}
}

Boot::registerClass(InternalTracker::class, 'gitea.repository.InternalTracker');
