<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents settings for an internal tracker.
 */
class InternalTracker {
	/**
	 * @var bool
	 * Value indicating whether to allow only contributors to track time.
	 */
	public $allowOnlyContributorsToTrackTime;
	/**
	 * @var bool
	 * Value indicating whether to enable dependencies for issues and pull requests.
	 */
	public $enableIssueDependencies;
	/**
	 * @var bool
	 * Value indicating whether to enable the time tracking.
	 */
	public $enableTimeTracker;

	/**
	 * Creates a new internal tracker.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->enableTimeTracker = false;
		$this->enableIssueDependencies = false;
		$this->allowOnlyContributorsToTrackTime = false;
		if ($data !== null) {
			if (\Reflect::hasField($data, "allow_only_contributors_to_track_time")) {
				$this->allowOnlyContributorsToTrackTime = \Reflect::field($data, "allow_only_contributors_to_track_time");
			}
			if (\Reflect::hasField($data, "enable_issue_dependencies")) {
				$this->enableIssueDependencies = \Reflect::field($data, "enable_issue_dependencies");
			}
			if (\Reflect::hasField($data, "enable_time_tracker")) {
				$this->enableTimeTracker = \Reflect::field($data, "enable_time_tracker");
			}
		}
	}
}

Boot::registerClass(InternalTracker::class, 'gitea.repository.InternalTracker');
