<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents a set of permissions.
 */
class Permission {
	/**
	 * @var bool
	 * Value indicating whether administrator access is allowed.
	 */
	public $admin;
	/**
	 * @var bool
	 * Value indicating whether pull is allowed.
	 */
	public $pull;
	/**
	 * @var bool
	 * Value indicating whether push is allowed.
	 */
	public $push;

	/**
	 * Creates a new user from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return Permission
	 */
	public static function fromJson ($map) {
		$model = new Permission();
		if (\Reflect::hasField($map, "admin")) {
			$model->admin = \Reflect::field($map, "admin");
		}
		if (\Reflect::hasField($map, "pull")) {
			$model->pull = \Reflect::field($map, "pull");
		}
		if (\Reflect::hasField($map, "push")) {
			$model->push = \Reflect::field($map, "push");
		}
		return $model;
	}

	/**
	 * Creates a new set of permissions.
	 * 
	 * @return void
	 */
	public function __construct () {
		$this->push = false;
		$this->pull = false;
		$this->admin = false;
	}
}

Boot::registerClass(Permission::class, 'gitea.repository.Permission');
