<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Represents a set of permissions.
 */
class Permission {
	/**
	 * @var bool
	 * Value indicating whether administrator access is allowed.
	 */
	public $admin;
	/**
	 * @var bool
	 * Value indicating whether pull is allowed.
	 */
	public $pull;
	/**
	 * @var bool
	 * Value indicating whether push is allowed.
	 */
	public $push;

	/**
	 * Creates a new set of permissions.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->push = false;
		$this->pull = false;
		$this->admin = false;
		if ($data !== null) {
			if (\Reflect::hasField($data, "admin")) {
				$this->admin = \Reflect::field($data, "admin");
			}
			if (\Reflect::hasField($data, "pull")) {
				$this->pull = \Reflect::field($data, "pull");
			}
			if (\Reflect::hasField($data, "push")) {
				$this->push = \Reflect::field($data, "push");
			}
		}
	}
}

Boot::registerClass(Permission::class, 'gitea.repository.Permission');
