<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\repository;

use \php\Boot;

/**
 * Provides meta information of a repository.
 */
class RepositoryMeta {
	/**
	 * @var string
	 * The full name.
	 */
	public $fullName;
	/**
	 * @var int
	 * The repository identifier.
	 */
	public $id;
	/**
	 * @var string
	 * The repository name.
	 */
	public $name;
	/**
	 * @var string
	 * The username of the repository owner.
	 */
	public $owner;

	/**
	 * Creates new repository metadata.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->owner = "";
		$this->name = "";
		$this->id = -1;
		$this->fullName = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "full_name") && is_string(\Reflect::field($data, "full_name"))) {
				$this->fullName = \Reflect::field($data, "full_name");
			}
			if (\Reflect::hasField($data, "id") && Boot::isOfType(\Reflect::field($data, "id"), Boot::getClass('Int'))) {
				$this->id = \Reflect::field($data, "id");
			}
			if (\Reflect::hasField($data, "name") && is_string(\Reflect::field($data, "name"))) {
				$this->name = \Reflect::field($data, "name");
			}
			if (\Reflect::hasField($data, "owner") && is_string(\Reflect::field($data, "owner"))) {
				$this->owner = \Reflect::field($data, "owner");
			}
		}
	}
}

Boot::registerClass(RepositoryMeta::class, 'gitea.repository.RepositoryMeta');
