<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\misc;

use \php\Boot;

/**
 * Wraps the version of the Gitea server.
 */
class ServerVersion {
	/**
	 * @var string
	 * The version number.
	 */
	public $version;

	/**
	 * Creates a new server version.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->version = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "version")) {
				$this->version = \Reflect::field($data, "version");
			}
		}
	}
}

Boot::registerClass(ServerVersion::class, 'gitea.misc.ServerVersion');
