<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\misc;

use \php\Boot;

/**
 * Wraps the version of the Gitea server.
 */
class ServerVersion {
	/**
	 * @var string
	 * The version number.
	 */
	public $version;

	/**
	 * Creates a new server version from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return ServerVersion
	 */
	public static function fromJson ($map) {
		return new ServerVersion((\Reflect::hasField($map, "version") ? \Reflect::field($map, "version") : ""));
	}

	/**
	 * Creates a new server version.
	 * 
	 * @param string $version
	 * 
	 * @return void
	 */
	public function __construct ($version) {
		$this->version = $version;
	}
}

Boot::registerClass(ServerVersion::class, 'gitea.misc.ServerVersion');
