<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\organization;

use \php\Boot;

/**
 * Represents an organization.
 */
class Organization {
	/**
	 * @var string
	 * The URL of the organization's avatar.
	 */
	public $avatarUrl;
	/**
	 * @var string
	 * The organization description.
	 */
	public $description;
	/**
	 * @var string
	 * The full name.
	 */
	public $fullName;
	/**
	 * @var int
	 * The organization identifier.
	 */
	public $id;
	/**
	 * @var string
	 * The organization's location.
	 */
	public $location;
	/**
	 * @var bool
	 * Value indicating whether the repository administrator can change access to teams.
	 */
	public $repoAdminCanChangeTeamAccess;
	/**
	 * @var string
	 * The name of the organization account.
	 */
	public $username;
	/**
	 * @var string
	 * The organization visibility.
	 */
	public $visibility;
	/**
	 * @var string
	 * The URL of the organization's website.
	 */
	public $website;

	/**
	 * Creates a new organization from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return Organization
	 */
	public static function fromJson ($map) {
		$model = new Organization((\Reflect::hasField($map, "id") && Boot::isOfType(\Reflect::field($map, "id"), Boot::getClass('Int')) ? \Reflect::field($map, "id") : -1));
		if (\Reflect::hasField($map, "avatar_url") && is_string(\Reflect::field($map, "avatar_url"))) {
			$model->avatarUrl = \Reflect::field($map, "avatar_url");
		}
		if (\Reflect::hasField($map, "description") && is_string(\Reflect::field($map, "description"))) {
			$model->description = \Reflect::field($map, "description");
		}
		if (\Reflect::hasField($map, "full_name") && is_string(\Reflect::field($map, "full_name"))) {
			$model->fullName = \Reflect::field($map, "full_name");
		}
		if (\Reflect::hasField($map, "location") && is_string(\Reflect::field($map, "location"))) {
			$model->location = \Reflect::field($map, "location");
		}
		if (\Reflect::hasField($map, "repo_admin_change_team_access") && is_bool(\Reflect::field($map, "repo_admin_change_team_access"))) {
			$model->repoAdminCanChangeTeamAccess = \Reflect::field($map, "repo_admin_change_team_access");
		}
		if (\Reflect::hasField($map, "username") && is_string(\Reflect::field($map, "username"))) {
			$model->username = \Reflect::field($map, "username");
		}
		if (\Reflect::hasField($map, "visibility") && is_string(\Reflect::field($map, "visibility"))) {
			$model->visibility = \Reflect::field($map, "visibility");
		}
		if (\Reflect::hasField($map, "website") && is_string(\Reflect::field($map, "website"))) {
			$model->website = \Reflect::field($map, "website");
		}
		return $model;
	}

	/**
	 * Creates a new organization.
	 * 
	 * @param int $id
	 * 
	 * @return void
	 */
	public function __construct ($id) {
		$this->website = "";
		$this->visibility = "private";
		$this->username = "";
		$this->repoAdminCanChangeTeamAccess = false;
		$this->location = "";
		$this->fullName = "";
		$this->description = "";
		$this->avatarUrl = "";
		$this->id = $id;
	}
}

Boot::registerClass(Organization::class, 'gitea.organization.Organization');
