<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\hook;

use \php\Boot;

/**
 * Represents the author or committer of a commit.
 */
class PayloadUser {
	/**
	 * @var string
	 * The mail address.
	 */
	public $email;
	/**
	 * @var string
	 * The full name.
	 */
	public $name;
	/**
	 * @var string
	 * The name of the user account.
	 */
	public $username;

	/**
	 * Creates a new payload user from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return PayloadUser
	 */
	public static function fromJson ($map) {
		$model = (\Reflect::hasField($map, "name") ? \Reflect::field($map, "name") : "");
		$model1 = new PayloadUser($model, (\Reflect::hasField($map, "email") ? \Reflect::field($map, "email") : ""));
		if (\Reflect::hasField($map, "username")) {
			$model1->username = \Reflect::field($map, "username");
		}
		return $model1;
	}

	/**
	 * Creates a new payload user.
	 * 
	 * @param string $name
	 * @param string $email
	 * 
	 * @return void
	 */
	public function __construct ($name, $email) {
		$this->username = "";
		$this->email = $email;
		$this->name = $name;
	}
}

Boot::registerClass(PayloadUser::class, 'gitea.hook.PayloadUser');
