<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea\hook;

use \php\Boot;

/**
 * Represents the author or committer of a commit.
 */
class PayloadUser {
	/**
	 * @var string
	 * The mail address.
	 */
	public $email;
	/**
	 * @var string
	 * The full name.
	 */
	public $name;
	/**
	 * @var string
	 * The name of the user account.
	 */
	public $username;

	/**
	 * Creates a new payload user.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->username = "";
		$this->name = "";
		$this->email = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "email")) {
				$this->email = \Reflect::field($data, "email");
			}
			if (\Reflect::hasField($data, "name")) {
				$this->name = \Reflect::field($data, "name");
			}
			if (\Reflect::hasField($data, "username")) {
				$this->username = \Reflect::field($data, "username");
			}
		}
	}
}

Boot::registerClass(PayloadUser::class, 'gitea.hook.PayloadUser');
