<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea;

use \php\Boot;

/**
 * An API error with a message.
 */
class ApiError {
	/**
	 * @var string
	 * A message describing the error.
	 */
	public $message;
	/**
	 * @var string
	 * The URL that is the source of the error.
	 */
	public $url;

	/**
	 * Creates a new heatmap data from the specified JSON map.
	 * 
	 * @param mixed $map
	 * 
	 * @return ApiError
	 */
	public static function fromJson ($map) {
		$tmp = (\Reflect::hasField($map, "message") ? \Reflect::field($map, "message") : "");
		return new ApiError($tmp, (\Reflect::hasField($map, "url") ? \Reflect::field($map, "url") : ""));
	}

	/**
	 * Creates a new API error.
	 * 
	 * @param string $message
	 * @param string $url
	 * 
	 * @return void
	 */
	public function __construct ($message, $url) {
		$this->message = $message;
		$this->url = $url;
	}
}

Boot::registerClass(ApiError::class, 'gitea.ApiError');
