<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea;

use \php\Boot;

/**
 * An API error with a message.
 */
class ApiError {
	/**
	 * @var string
	 * A message describing the error.
	 */
	public $message;
	/**
	 * @var string
	 * The URL that is the source of the error.
	 */
	public $url;

	/**
	 * Creates a new API error.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->url = "";
		$this->message = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "message")) {
				$this->message = \Reflect::field($data, "message");
			}
			if (\Reflect::hasField($data, "url")) {
				$this->url = \Reflect::field($data, "url");
			}
		}
	}
}

Boot::registerClass(ApiError::class, 'gitea.ApiError');
