<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea;

use \php\Boot;

/**
 * Provides meta information of a commit.
 */
class CommitMeta {
	/**
	 * @var string
	 * The commit hash.
	 */
	public $sha;
	/**
	 * @var string
	 * The URL to the commit's history.
	 */
	public $url;

	/**
	 * Creates new commit metadata.
	 * 
	 * @param mixed $data
	 * 
	 * @return void
	 */
	public function __construct ($data = null) {
		$this->url = "";
		$this->sha = "";
		if ($data !== null) {
			if (\Reflect::hasField($data, "sha")) {
				$this->sha = \Reflect::field($data, "sha");
			}
			if (\Reflect::hasField($data, "url")) {
				$this->url = \Reflect::field($data, "url");
			}
		}
	}
}

Boot::registerClass(CommitMeta::class, 'gitea.CommitMeta');
