<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace gitea;

use \php\Boot;

/**
 * Provides static methods for managing dates.
 */
class DateTools {
	/**
	 * Parses an ISO 8601 date string into a `Date` instance.
	 * Returns a `null` reference if an error occurred.
	 * 
	 * @param string $dateString
	 * 
	 * @return \Date
	 */
	public static function parseIsoString ($dateString) {
		$timestamp = null;
		try {
			$timestamp = (new \DateTime($dateString))->getTimestamp();
		} catch(\Throwable $_g) {
			$timestamp = null;
		}
		if ($timestamp !== null) {
			return \Date::fromTime($timestamp * 1000);
		} else {
			return null;
		}
	}
}

Boot::registerClass(DateTools::class, 'gitea.DateTools');
